import { defineSchema, section } from "@classytic/formkit/server";
import { money } from "../fields";
import { defineSchedule } from "./define";

/**
 * Net income (loss) for income tax purposes (T2SCH1).
 *
 * GENERATED from the form definition in @classytic/ca-tax:
 *   npx tsx packages/ca-tax/scripts/emit-ui-schedule.ts
 *
 * Ultimately from research/sources/cra-forms/T2SCH01-net-income-for-tax.pdf,
 * retrieved 2026-08-11.
 *
 * Every field is a real line, captioned as the form captions it and named for
 * the number it is transmitted under — so what a preparer types is already in
 * filing shape, with no mapping step to get wrong. Totals and figures carried
 * from other schedules are omitted: rendering them editable invites someone to
 * overwrite a computed number, and the return then does not foot.
 */
export const netIncome = defineSchedule({
  key: "netIncome",
  num: "001",
  label: "Net Income for Tax (S1)",
  hint: "Book-to-tax reconciliation",
  schema: defineSchema({
    sections: [
      section(
        "add-1",
        "Add",
        [
          money("lines.101", "Provision for income taxes – current (line 101)", { description: "The current provision only; the deferred provision is line 102." }),
          money("lines.102", "Provision for income taxes – deferred (line 102)"),
          money("lines.103", "Interest and penalties on taxes (line 103)"),
          money("lines.104", "Amortization of tangible assets (line 104)", { description: "Book amortization. The tax equivalent is capital cost allowance at line 403." }),
          money("lines.105", "Amortization of natural resource assets (line 105)"),
          money("lines.106", "Amortization of intangible assets (line 106)"),
          money("lines.110", "Loss in equity of subsidiaries and affiliates (line 110)"),
          money("lines.111", "Loss on disposal of assets (line 111)"),
          money("lines.114", "Political contributions (line 114)"),
          money("lines.115", "Holdbacks (line 115)"),
          money("lines.116", "Deferred and prepaid expenses (line 116)"),
          money("lines.117", "Depreciation in inventory – end of year (line 117)"),
          money("lines.118", "Scientific research expenditures deducted per financial statements (line 118)"),
          money("lines.119", "Capitalized interest (line 119)"),
          money("lines.120", "Non-deductible club dues and fees (line 120)"),
          money("lines.121", "Non-deductible meals and entertainment expenses (line 121)", { description: "Half of meals and entertainment is denied by ITA s.67.1 — enter the disallowed half here, not the whole expense." }),
          money("lines.122", "Non-deductible automobile expenses (line 122)"),
          money("lines.123", "Non-deductible life insurance premiums (line 123)"),
          money("lines.124", "Non-deductible company pension plans (line 124)"),
          money("lines.126", "Reserves from financial statements – balance at the end of the year (line 126)"),
          money("lines.127", "Soft costs on construction and renovation of buildings (line 127)"),
          money("lines.128", "Non-deductible fines and penalties under section 67.6 (line 128)", { description: "ITA s.67.6 denies fines and penalties outright." }),
          money("lines.129", "Income or loss for tax purposes – partnerships (line 129)"),
          money("lines.132", "Income or loss for tax purposes – joint ventures (line 132)"),
        ],
        {
          variant: "card",
          cols: 2,
          description: "Amounts charged in the books that tax does not allow, and amounts taxable that the books did not record. Book amortization is added here at line 104 and replaced by capital cost allowance at line 403 — the two are the same size and opposite in sign, and only the line number distinguishes them.",
        },
      ),
      section(
        "deduct-2",
        "Deduct",
        [
          money("lines.401", "Gain on disposal of assets per financial statements (line 401)"),
          money("lines.407", "Foreign non-business tax deduction under subsection 20(12) (line 407)"),
          money("lines.408", "Holdbacks (line 408)"),
          money("lines.409", "Deferred and prepaid expenses (line 409)"),
          money("lines.410", "Depreciation in inventory – end of prior year (line 410)"),
          money("lines.414", "Reserves from financial statements – balance at the beginning of the year (line 414)"),
          money("lines.418", "Incorporation expenses under paragraph 20(1)(b) (line 418)"),
        ],
        {
          variant: "card",
          cols: 2,
          description: "Deductions tax allows that the books did not take, and book income that is not taxable. Capital cost allowance, terminal loss and the reserve continuity arrive from their own schedules.",
        },
      ),
      section(
        "add-3",
        "Add — continued",
        [
          money("lines.201", "Accounts payable and accruals for cash basis – closing (line 201)"),
          money("lines.202", "Accounts receivable and prepaid for cash basis – opening (line 202)"),
          money("lines.203", "Accrual inventory – opening (line 203)"),
          money("lines.204", "Accrued dividends – prior year (line 204)"),
          money("lines.206", "Capital items expensed (line 206)"),
          money("lines.208", "Debt issue expense (line 208)"),
          money("lines.209", "Deemed dividend income (line 209)"),
          money("lines.210", "Deemed interest on loans to non-residents (line 210)"),
          money("lines.211", "Deemed interest received (line 211)"),
          money("lines.212", "Development expenses claimed in current year (line 212)"),
          money("lines.213", "Dividend stop-loss adjustment (line 213)"),
          money("lines.214", "Dividends credited to the investment account (line 214)"),
          money("lines.215", "Exploration expenses claimed in current year (line 215)"),
          money("lines.216", "Financing fees deducted in books (line 216)"),
          money("lines.217", "Foreign accrual property income (line 217)"),
          money("lines.218", "Foreign affiliate property income (line 218)"),
          money("lines.219", "Foreign exchange included in retained earnings (line 219)"),
          money("lines.220", "Gain on settlement of debt (line 220)"),
          money("lines.221", "Interest paid on income debentures (line 221)"),
          money("lines.222", "Limited partnership losses from Schedule 4 (line 222)"),
          money("lines.224", "Mandatory inventory adjustment – included in current year (line 224)"),
          money("lines.226", "Non-deductible advertising (line 226)"),
          money("lines.227", "Non-deductible interest (line 227)"),
          money("lines.228", "Non-deductible legal and accounting fees (line 228)"),
          money("lines.229", "Optional value of inventory – included in current year (line 229)"),
          money("lines.230", "Other expenses from financial statements (line 230)"),
          money("lines.231", "Recapture of SR&ED expenditures from Form T661 (line 231)"),
          money("lines.232", "Resource amounts deducted (line 232)"),
          money("lines.233", "Restricted farm losses – current year from Schedule 4 (line 233)"),
          money("lines.234", "Sales tax assessments (line 234)"),
          money("lines.235", "Share issue expense (line 235)"),
          money("lines.236", "Write-down of capital property (line 236)"),
          money("lines.237", "Amounts received in respect of qualifying environmental trust per paragraphs 12(1)(z.1) and 12(1)(z.2) (line 237)"),
          money("lines.238", "Contractors' completion method adjustment: revenue net of costs on contracts under two years – previous year (line 238)"),
          money("lines.239", "Taxable/non-deductible other comprehensive income items (line 239)"),
          money("lines.248", "Book loss of joint ventures (line 248)"),
          money("lines.249", "Book loss of partnerships (line 249)"),
          money("lines.250", "Hybrid mismatch amount under subsection 18.4(4) or 12.7(3) (line 250)"),
          money("lines.251", "Excess IFE under subsection 18.2(2) from Schedule 130 (line 251)"),
          money("lines.252", "Partnership IFE add-back under paragraph 12(1)(l.2) from Schedule 130 (line 252)"),
          money("lines.253", "Non-deductible interest under subsection 18(4) (line 253)"),
          money("lines.254", "Partnership interest deduction add-back under paragraph 12(1)(l.1) (line 254)"),
          money("lines.296", "Total of column 2 (line 296)"),
        ],
        {
          variant: "card",
          cols: 2,
          description: "The continuation of the additions. Its total returns to line 199 on page 1, so nothing here escapes the line 500 total.",
          collapsible: true,
          defaultCollapsed: true,
        },
      ),
      section(
        "deduct-4",
        "Deduct — continued",
        [
          money("lines.300", "Accounts payable and accruals for cash basis – opening (line 300)"),
          money("lines.301", "Accounts receivable and prepaid for cash basis – closing (line 301)"),
          money("lines.302", "Accrual inventory – closing (line 302)"),
          money("lines.303", "Accrued dividends – current year (line 303)"),
          money("lines.304", "Bad debt (line 304)"),
          money("lines.306", "Equity in income from subsidiaries or affiliates (line 306)"),
          money("lines.307", "Exempt income under section 81 (line 307)"),
          money("lines.309", "Mandatory inventory adjustment – included in prior year (line 309)"),
          money("lines.310", "Contributions to a qualifying environmental trust (line 310)"),
          money("lines.311", "Non-Canadian advertising expenses – broadcasting (line 311)"),
          money("lines.312", "Non-Canadian advertising expenses – printed materials (line 312)"),
          money("lines.313", "Optional value of inventory – included in prior year (line 313)"),
          money("lines.314", "Other income from financial statements (line 314)"),
          money("lines.315", "Payments made for allocations in proportion to borrowing and bonus interest payments from Schedule 17 (line 315)"),
          money("lines.316", "Contractors' completion method adjustment: revenue net of costs on contracts under two years – current year (line 316)"),
          money("lines.347", "Non-taxable/deductible other comprehensive income items (line 347)"),
          money("lines.348", "Book income of joint venture (line 348)"),
          money("lines.349", "Book income of partnership (line 349)"),
          money("lines.350", "Adjustment for hybrid mismatch amount under paragraph 20(1)(yy) (line 350)"),
          money("lines.340", "Canadian development expenses from Schedule 12 (line 340)"),
          money("lines.341", "Canadian exploration expenses from Schedule 12 (line 341)"),
          money("lines.342", "Canadian oil and gas property expenses from Schedule 12 (line 342)"),
          money("lines.344", "Depletion from Schedule 12 (line 344)"),
          money("lines.345", "Foreign exploration and development expenses from Schedule 12 (line 345)"),
          money("lines.396", "Total of column 2 (line 396)"),
        ],
        {
          variant: "card",
          cols: 2,
          description: "The continuation of the deductions. Its total returns to line 499 on page 2. These are deductions despite carrying 300-series numbers.",
          collapsible: true,
          defaultCollapsed: true,
        },
      ),
    ],
  }),
});
